### ISSUE TITLE
Download SQL Server Express Language

### ISSUE THREAD

**Issue by Piixell** [jimm98y/MSSQLEXPRESS-M1-Install#1]
The download that you've placed in your scripts depends on my language, for example: I'm from Italy, and if I go on that link that you placed in the ps1 script, it will automatically download the _ITA version and not the _ENU. 

I suggest to specify that users need to specify their language, instead the installer will not work because it cannot find the directory.

**Comment by jimm98y** [comment]
The installer should now correctly enforce ENU regardless of the system culture. Tested on Czech OS and it seems to be working.
