### ISSUE TITLE
Can not run .bat file

### ISSUE THREAD

**Issue by amayavne** [jimm98y/MSSQLEXPRESS-M1-Install#10]
I couldn't download the script so I copied the raw text and made a .bat file out of it. However when I open it, it runs for a few seconds, powershell boots up and closes immediately.

**Comment by jimm98y** [comment]
Did you also copy the PowerShell (*.ps1) and include it in the same directory as the *.bat file? Also the file name for the PowerShell must be the same as in this repo.
