### ISSUE TITLE
Unable to Start SQL Server 2022 service

### ISSUE THREAD

**Issue by cigoic** [jimm98y/MSSQLEXPRESS-M1-Install#11]
Hi, I just started a fresh Win 11 Pro installation and tried to install SQL Server 2022 Developer version today.

Made some script revise in order to install Traditional Chinese version. Somehow, the installation is finished successfully. The SQL service is unable to launch at all. Restart the OS or reinstall SQL Server did not solve.

Any suggestion? Thanks.

[install2022Developer.ps1.txt](https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/files/10838649/install2022Developer.ps1.txt)

![截圖 2023-02-27 下午6 23 09](https://user-images.githubusercontent.com/2939228/221539696-b5438650-60f2-45af-9004-025150f3337d.jpg)

**Comment by jimm98y** [comment]
Should be fixed using the new installers or scripts.
