### ISSUE TITLE
Get Permission Denied Errors

### ISSUE THREAD

**Issue by rar000** [jimm98y/MSSQLEXPRESS-M1-Install#12]
Hello I am a noob so I hope you can help. 

I just installed windows 11 arm via on my Parrells for Mac  (using m1 mac mini)

I tried to open your bat file it flashed and went away, so i attempted to use powershell and copy/paste  into there
Everything was installing as it should be for sql server, however towards the end i noticed in powershell there were numerous permission denied for hkey 
I can attached a screenshot link  below

https://imgur.com/a/H9PKvRW

**Comment by jimm98y** [comment]
The *.bat file will launch PowerShell as Administrator. If you are trying to run PowerShell directly, you have to open it as an Administrator as well, otherwise you'll have permission errors.
