### ISSUE TITLE
Copy-Item : Cannot find path

### ISSUE THREAD

**Issue by MuhammadAliYousaf** [jimm98y/MSSQLEXPRESS-M1-Install#15]
Please see attach image for error detail. Any help will be appreciated.
<img width="1158" alt="Screenshot 2023-04-13 at 11 30 02 AM" src="https://user-images.githubusercontent.com/2880208/231673441-175cde26-3121-4983-91a8-7f0e88ad42aa.png">

**Comment by khanakia** [comment]
I am having the same issue

**Comment by khanakia** [comment]
@MuhammadAliYousaf 
I was able to install it.

- Uninstall all the existing SQL server including client, SDK etc. through `appwiz.cpl`
- Delete the directory if exists on `C:/Program Files/Microsoft SQL Server`
- Copy the script into the `C:\` directory and run it as administrator

**Comment by jacklawry** [comment]
> Please see attach image for error detail. Any help will be appreciated.
> <img alt="Screenshot 2023-04-13 at 11 30 02 AM" width="1158" src="https://user-images.githubusercontent.com/2880208/231673441-175cde26-3121-4983-91a8-7f0e88ad42aa.png">

I had the same error installing SQL Server 2022 Express on a Mac M2 but it did install it and it works fine.
