### ISSUE TITLE
ResourceExists: (C:\Program File...ERVER\MSSQL\Log:String) [New-Item], IOException

### ISSUE THREAD

**Issue by TomLiu-GitHub** [jimm98y/MSSQLEXPRESS-M1-Install#18]
New-Item : 具有指定名称 C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Log 的项已存在。
所在位置 C:\Soft\MSSQLEXPRESS-M1-Install\src\install2022Developer.ps1:88 字符: 1
+ New-Item -Path $logDir -ItemType Directory
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\Program File...ERVER\MSSQL\Log:String) [New-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.NewItemCommand

New-Item : 具有指定名称 C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA 的项已存在。
所在位置 C:\Soft\MSSQLEXPRESS-M1-Install\src\install2022Developer.ps1:91 字符: 1
+ New-Item -Path $dataDir -ItemType Directory
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\Program File...RVER\MSSQL\DATA:String) [New-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.NewItemCommand

Copy-Item : 找不到路径“C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Binn\Templates\master.mdf”，因为
该路径不存在。
所在位置 C:\Soft\MSSQLEXPRESS-M1-Install\src\install2022Developer.ps1:120 字符: 1
+ Copy-Item -Path "$installedPath\Binn\Templates\master.mdf" -Destinati ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...ates\master.mdf:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : 找不到路径“C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Binn\Templates\mastlog.ldf”，因为该路径不存在。
所在位置 C:\Soft\MSSQLEXPRESS-M1-Install\src\install2022Developer.ps1:121 字符: 1
+ Copy-Item -Path "$installedPath\Binn\Templates\mastlog.ldf" -Destinat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...tes\mastlog.ldf:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

New-ItemProperty : 找不到路径“HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQLServer\Parameters”
，因为该路
径不存在。
所在位置 C:\Soft\MSSQLEXPRESS-M1-Install\src\install2022Developer.ps1:126 字符: 1
+ New-ItemProperty -Path $registryPath -Name $name -Value $value -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...rver\Parameters:String) [New-ItemProperty], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.NewItemPropertyCommand                                                                                                                                                 New-ItemProperty : 找找不不到到路路径径“HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQLServer\Parameters” ，，因因为为该该路路                                                                                          
所在位置 C:\Soft\MSSQLEXPRESS-M1-Install\src\install2022Developer.ps1:129 字符: 1
+ New-ItemProperty -Path $registryPath -Name $name -Value $value -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...rver\Parameters:String) [New-ItemProperty], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.NewItemPropertyCommand

New-ItemProperty : 找不到路径“HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQLServer\Parameters”
，因为该路
径不存在。
所在位置 C:\Soft\MSSQLEXPRESS-M1-Install\src\install2022Developer.ps1:132 字符: 1
+ New-ItemProperty -Path $registryPath -Name $name -Value $value -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...rver\Parameters:String) [New-ItemProperty], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.NewItemPropertyCommand

**Comment by Jawiiki** [comment]
好兄弟，把系统语言修改成英文就好了

**Comment by jimm98y** [comment]
Should be fixed using the new installers or scripts.

**Comment by Jawiiki** [comment]
No need to use new scripts, just change your Windows language to English
