### ISSUE TITLE
The service name is invalid. More help is available by typing NET HELPMSG 2185. - Macbook Pro M2

### ISSUE THREAD

**Issue by rngallen** [jimm98y/MSSQLEXPRESS-M1-Install#19]
` Exception calling "SetAccessRule" with "1" argument(s): "Some or all identity references could not be translated."
At C:\Users\ngallen\AppData\Local\Temp\Temp1_MSSQLEXPRESS-M1-Install-main.zip\MSSQLEXPRESS-M1-Install-main\src\install2
022Developer.ps1:98 char:1
+ $acl.SetAccessRule($accessRule)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException

Exception calling "SetAccessRule" with "1" argument(s): "Some or all identity references could not be translated."
At C:\Users\ngallen\AppData\Local\Temp\Temp1_MSSQLEXPRESS-M1-Install-main.zip\MSSQLEXPRESS-M1-Install-main\src\install2
022Developer.ps1:103 char:1
+ $acl.SetAccessRule($accessRule)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException

Copy-Item : Cannot find path 'C:\Program Files\Microsoft SQL
Server\MSSQL16.MSSQLSERVER\MSSQL\Binn\Templates\master.mdf' because it does not exist.
At C:\Users\ngallen\AppData\Local\Temp\Temp1_MSSQLEXPRESS-M1-Install-main.zip\MSSQLEXPRESS-M1-Install-main\src\install2
022Developer.ps1:120 char:1
+ Copy-Item -Path "$installedPath\Binn\Templates\master.mdf" -Destinati ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...ates\master.mdf:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand                                 Writing web request                                                                                                                                  (Number of bytes written: 86Copy-Item : Cannot find path 'C:\Program Files\Microsoft SQL                                                                                         Server\MSSQL16.MSSQLSERVER\MSSQL\Binn\Templates\mastlog.ldf' because it does not exist.                                 ESS-M1-Install-main\src\install2
022Developer.ps1:121 char:1
+ Copy-Item -Path "$installedPath\Binn\Templates\mastlog.ldf" -Destinat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...tes\mastlog.ldf:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

New-ItemProperty : Cannot find path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL
Server\MSSQL16.MSSQLSERVER\MSSQLServer\Parameters' because it does not exist.
At C:\Users\ngallen\AppData\Local\Temp\Temp1_MSSQLEXPRESS-M1-Install-main.zip\MSSQLEXPRESS-M1-Install-main\src\install2
022Developer.ps1:126 char:1
+ New-ItemProperty -Path $registryPath -Name $name -Value $value -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...rver\Parameters:String) [New-ItemProperty], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.NewItemPropertyCommand

New-ItemProperty : Cannot find path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL
Server\MSSQL16.MSSQLSERVER\MSSQLServer\Parameters' because it does not exist.
At C:\Users\ngallen\AppData\Local\Temp\Temp1_MSSQLEXPRESS-M1-Install-main.zip\MSSQLEXPRESS-M1-Install-main\src\install2
022Developer.ps1:129 char:1
+ New-ItemProperty -Path $registryPath -Name $name -Value $value -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...rver\Parameters:String) [New-ItemProperty], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.NewItemPropertyCommand

New-ItemProperty : Cannot find path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL
Server\MSSQL16.MSSQLSERVER\MSSQLServer\Parameters' because it does not exist.
At C:\Users\ngallen\AppData\Local\Temp\Temp1_MSSQLEXPRESS-M1-Install-main.zip\MSSQLEXPRESS-M1-Install-main\src\install2
022Developer.ps1:132 char:1
+ New-ItemProperty -Path $registryPath -Name $name -Value $value -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...rver\Parameters:String) [New-ItemProperty], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.NewItemPropertyCommand`

**Comment by Corneliuus** [comment]
I have the same problem on M2 MacBook Air

**Comment by ginolabit** [comment]
same here
MacBook Air M2

Any chance to fix this?
Thanks

**Comment by rngallen** [comment]
Make sure your windows user has password

**Comment by HMside** [comment]
As a german user it helped me to change the following line from the .ps1.

`$sqlInstallArgs = "/qs /ACTION=Install /FEATURES=SQLEngine /INSTANCENAME=$instanceName /ENU /IACCEPTSQLSERVERLICENSETERMS /UPDATEENABLED=false /USEMICROSOFTUPDATE=false"`
to
`$sqlInstallArgs = "/qs /ACTION=Install /FEATURES=SQLEngine /INSTANCENAME=$instanceName /IACCEPTSQLSERVERLICENSETERMS /UPDATEENABLED=false /USEMICROSOFTUPDATE=false"`

**Comment by newky2k** [comment]
Please note after some digging around and running the SETUP.exe directly, path length is a factor in the success.  SQL Setup will fail silently if the path is long than 260 characters

**Comment by twaibs23** [comment]
I have been trying for the last day to get SQL 2019 running on Windows 11 (Parallels) on my M2 Max. Getting the same error that @rngallen posted above. Any ideas?

**Comment by rngallen** [comment]
Make sure your windows user has password as by default it install MSSQL with windows authentication. @twaibs23

**Comment by twaibs23** [comment]
@rngallen Script seemed to complete this time, however now I'm getting the same Windows Update error message that I've gotten all along when trying to install 2019 or 2022 SQL on my machine. Anyone able to give me a hand and take a look? Trying to get 2019 installed to work with Webgility.

**Comment by TroyT868** [comment]
Just a few notes. I got it working but didn't use a Microsoft account when setting up Windows 11. I created a standard local account setup as a member of the local administrators group with a password assigned to it and got all versions of the script to install their respective SQL editions without any issues under that usage scenario. If you're using a Microsoft account to sign in I'd ditch that and go with a local admin account with a password instead to get things going. For security purposes you shouldn't use an account with local admin privileges as your daily driver account unless you are security conscious and know what you're doing. Use a non-admin account for that but don't use a Microsoft account with Windows 10 or 11 either way if you want to avoid a bunch of headaches....

**Comment by jimm98y** [comment]
Judging by the error it looks like an issue with getting the user - what is the output of "whoami" in PowerShell on the affected machine? Are you using Active Directory account? The scripts were tested with a personal Microsoft account. Also as @rngallen mentioned, the user account under which you are installing should probably have a password set.

**Comment by jimm98y** [comment]
Should be fixed using the new installers or scripts.
