### ISSUE TITLE
[Help Request] SQL Server 2022 Developer

### ISSUE THREAD

**Issue by cigoic** [jimm98y/MSSQLEXPRESS-M1-Install#2]
Hi,

Is it possible add support to install SQL Server 2022/2019 Developer version?
It fail to install via simply rename SQLExpr to SQLDev in the .ps file. Especially when the process comes to copy master.mdf, there is no existing path to find any .mdf file. =(

Thanks.

Attached file is the modified version. However, it looks like something is missing here.
[install2022.ps1.txt](https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/files/10496400/install2022.ps1.txt)

**Comment by cigoic** [comment]
By the way, here are screenshots.

![截圖 2023-01-25 下午1 40 42](https://user-images.githubusercontent.com/2939228/214488834-4b20402e-6f5e-4e3b-abdb-185add050f27.jpg)
![截圖 2023-01-25 下午1 40 51](https://user-images.githubusercontent.com/2939228/214488841-77ff1f49-a7ec-444d-ba35-3c742352254d.jpg)

**Comment by robybrigno** [comment]
I have the same problem. There is a solution?

**Comment by cigoic** [comment]
Hey,

I made some progress yesterday...Finally, SQL Server 2022 was installed successfully.
You could try to modify as shown below:
 
1. Replace "SSEI-Expr" to "SSEI-Dev"
2. Use "https://download.microsoft.com/download/c/c/9/cc9c6797-383c-4b24-8920-dc057c1de9d3/SQL2022-SSEI-Dev.exe" to Download Developer version of SQL Server 2022 for example.
3. $instanceName = "MSSQLSERVER"

[install2022.ps1.txt](https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/files/10505481/install2022.ps1.txt)

First, execute above script and it will fail to rebuild database. 
Then, I simply manually execute command in PowerShell instead.

`136 # rebuild databases
  137 $user = whoami
  138 Start-Process -FilePath "$setupFolderPath/SETUP.EXE" -ArgumentList "/QUIET /ACTION=REBUILDDATABASE /INSTANCENAME=$instanceName /SQLSYSADMINACCOUNTS=$user" -Wait`

1. Switch to $setupFolderPath folder, and find out current username with "woami" command.
2. `./SETUP.EXE /QUIET /ACTION=REBUILDDATABASE /INSTANCENAME=MSSQLSERVER /SQLSYSADMINACCOUNTS=PUT_YOURUSERNAME_HERE`
3. `net start MSSQLSERVER`

Though, SQL Server 2022 Developer could be installed. SQL LocalDB installed via VS 2022 will fail to be recognized inside Visual Studio itself. 

SSMS 19 can recognize and connect to SQL LocalDB, but VS 2022 cannot. I have no idea about this. 

Any suggestion? Thanks a lot!

**Comment by robybrigno** [comment]
sorry but how to fix this ?
<img width="1196" alt="Screenshot 2023-01-27 alle 08 35 30" src="https://user-images.githubusercontent.com/123560639/215032870-23cad015-fd91-449a-bbfe-dcd71455cdac.png">

**Comment by jimm98y** [comment]
> sorry but how to fix this ? <img alt="Screenshot 2023-01-27 alle 08 35 30" width="1196" src="https://user-images.githubusercontent.com/123560639/215032870-23cad015-fd91-449a-bbfe-dcd71455cdac.png">

Could you please send me a screenshot of the ./Temp directory when this error happens? In case it was deleted already by the script, then please restore it from the Recycle Bin. Looks like a problem with the language, but I've tried it on an US OS with Czech language pack and I could not reproduce the issue.

**Comment by robybrigno** [comment]
[](url)
<img width="1039" alt="Screenshot 2023-01-30 alle 20 27 08" src="https://user-images.githubusercontent.com/123560639/215598098-f3f33bdb-0fb6-4c19-bf0a-7fe7457d8dd7.png">
<img width="731" alt="Screenshot 2023-01-30 alle 22 22 31" src="https://user-images.githubusercontent.com/123560639/215598119-4b296a1d-d49d-42de-bdf4-23c039143e7f.png">
this is the image

**Comment by hynekk** [comment]
I had similar issue and then I uninstall everything and tried to install developer 19 version and all seems to work just fine.
