### ISSUE TITLE
Can you please provide info on how to modify script to change some installation parameters.

### ISSUE THREAD

**Issue by gchapel1** [jimm98y/MSSQLEXPRESS-M1-Install#21]
I need to create an SQL database instance with a particular instance name and using mixed mode authorization with a particular (sa) password.  The original installer allows you to set this parameters upon creation.  Your script defaults create a working database but don't have the proper parameters I need.  

I see that the instance name is easily changed with one of your parameters in the script but I didn't see how you were setting the authentication mode or how I would enter a password. 

Is there anyway you could document the parameters in your script so that others could create new databases with the proper parameters for their needs.  In otherwords, could you please document the key variables in the script that need to be changed to change installation parameters.

I have an example png file that I am attaching of the specific installation page from the original setup file that I need to modify.

Thanks

<img width="807" alt="Screenshot 2023-08-29 at 11 50 59 AM" src="https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/assets/66180616/c90e0088-7afc-404c-974f-50a22cf6c40c">

**Comment by jimm98y** [comment]
Could you perhaps use the SQL Management Studio and configure it there? The script was designed to get you started with some reasonable defaults. After it's installed, it's up to you to re-configure it to suit your needs. To do that, I'd suggest modifying the registry entries or using the SQL Management Studio which should have been installed automatically for you. To configure SQL in the Mixed Mode, please take a look here: [https://stackoverflow.com/questions/48481401/how-to-allow-sql-server-authentication-in-sql-server-2017-express](url)
