### ISSUE TITLE
Not installing on Windows 11 Installed in parallels on M1 mac

### ISSUE THREAD

**Issue by tegwin** [jimm98y/MSSQLEXPRESS-M1-Install#24]
I am getting a bunch of errors and its actually not installing but SSMS is installed, and I thought it. has installed but could not login.  So I uninstalled and reinstalled and keep getting the error

Directory: C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/28/2023   5:01 PM                Log
d-----        10/28/2023   5:01 PM                DATA
Exception calling "SetAccessRule" with "1" argument(s): "Some or all identity references could not be translated."
At C:\Users\christimm\Downloads\MSSQLEXPRESS-M1-Install-main\src\install2022Express.ps1:98 char:1
+ $acl.SetAccessRule($accessRule)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException

Exception calling "SetAccessRule" with "1" argument(s): "Some or all identity references could not be translated."
At C:\Users\christimm\Downloads\MSSQLEXPRESS-M1-Install-main\src\install2022Express.ps1:103 char:1
+ $acl.SetAccessRule($accessRule)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException

Copy-Item : Cannot find path 'C:\Program Files\Microsoft SQL
Server\MSSQL16.SQLEXPRESS\MSSQL\Binn\Templates\master.mdf' because it does not exist.
At C:\Users\christimm\Downloads\MSSQLEXPRESS-M1-Install-main\src\install2022Express.ps1:120 char:1
+ Copy-Item -Path "$installedPath\Binn\Templates\master.mdf" -Destinati ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...ates\master.mdf:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'C:\Program Files\Microsoft SQL
Server\MSSQL16.SQLEXPRESS\MSSQL\Binn\Templates\mastlog.ldf' because it does not exist.
At C:\Users\christimm\Downloads\MSSQLEXPRESS-M1-Install-main\src\install2022Express.ps1:121 char:1
+ Copy-Item -Path "$installedPath\Binn\Templates\mastlog.ldf" -Destinat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...tes\mastlog.ldf:String) [Copy-Item], ItemNotFoundExce
   ption

**Comment by TroyT868** [comment]
Are you using the batch file from an elevated command prompt to install SQL using these scripts or running the PowerShell scripts using PowerShell or PowerShell ISE? I had no issues with the scripts but ran the batch files from an elevated command prompt and got all editions to install using the scripts (2019 Express, 2019 Developer, 2022 Express and 2022 Developer). Which version have you tried installing?

**Comment by jimm98y** [comment]
Should be fixed using the new installers or scripts.
