### ISSUE TITLE
SQL server can't be reinstalled; it prompts an error when installed.

### ISSUE THREAD

**Issue by zhengyuanjun** [jimm98y/MSSQLEXPRESS-M1-Install#27]
SQL server can't be reinstalled; it prompts an error when installed.
I installed the SQL server first, then uninstalled it.  I tried to install it again but failed.
<img width="1119" alt="Snipaste_2024-02-01_08-57-44" src="https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/assets/26426113/0d8fdd2f-c4e5-490b-b038-abd8936e7057">

does only one know how to fix it

**Comment by jimm98y** [comment]
Should be fixed using the new installers or scripts.
