### ISSUE TITLE
SQL Agent is not installed

### ISSUE THREAD

**Issue by jimm98y** [jimm98y/MSSQLEXPRESS-M1-Install#3]
SQL Agent is not installed with the Developer version of the SQL Server.

**Comment by shennerf** [comment]
I noticed the same thing. I was able to get it to work by adding the missing registry keys (and associated key access), creating the missing account in SQLServer and assigning the access, and the missing folder and assigning the correct access.

**Comment by wags674** [comment]
> I noticed the same thing. I was able to get it to work by adding the missing registry keys (and associated key access), creating the missing account in SQLServer and assigning the access, and the missing folder and assigning the correct access.

I have the same problem. Can you provide me the steps you reference to get it to work?

**Comment by Disruptor85** [comment]
> > I noticed the same thing. I was able to get it to work by adding the missing registry keys (and associated key access), creating the missing account in SQLServer and assigning the access, and the missing folder and assigning the correct access.
> 
> I have the same problem. Can you provide me the steps you reference to get it to work?

I followed this tutorial here, and it is working, as simple as that using SSMS 19
https://www.mssqltips.com/sqlservertip/2729/how-to-start-sql-server-agent-when-agent-xps-show-disabled/

**Comment by jimm98y** [comment]
SQL Agent is now being installed using the new installers or scripts.
