### ISSUE TITLE
[Help Request] Windows auth login failed

### ISSUE THREAD

**Issue by faiqg** [jimm98y/MSSQLEXPRESS-M1-Install#31]
Using Parallels on MacBook Pro M1. Installed using Sql2022Developer.bat (let it download installer). 
Installation is complete. The SQL Server service seems to be running. 
When connecting to the instance using SSMS or SQLCMD, the error pops up. "Login failed for user "hostname\myuser.name"

![image](https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/assets/3004484/f767dd15-9bc6-480e-8272-b65bed638234)

I am sure i am missing something small. Could you please point me to a possible resolution?

**Comment by jimm98y** [comment]
In Advanced options in the connection dialog there should be something like "Trust server certificate". You have to check it.

**Comment by faiqg** [comment]
That checkbox is ticked in my case. Without that checked, i get a certificate related error. 
![image](https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/assets/3004484/ddf2a94f-5fac-48f1-bf1b-9c2d2afe4ebd)

**Comment by faiqg** [comment]
Opened SSMS as an Admin and viola! The installation needs elevated permissions, so makes sense the connections would too. 

Bonus for anyone wandering here in the future - [How to make any program always run as an administrator on Windows](https://www.wikihow.tech/Always-Run-a-Program-As-an-Administrator-on-Windows).
