### ISSUE TITLE
Failure to install using the installer

### ISSUE THREAD

**Issue by rda874** [jimm98y/MSSQLEXPRESS-M1-Install#33]
Hello- I tried the installer as you recommended but got this error. 
<img width="606" alt="Screenshot 2024-05-11 at 8 41 48 AM" src="https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/assets/160538570/b256aec8-2b78-4ed2-bf3d-576879066108">
[SQL_2019_Express_ARM64_20240510170810.log](https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/files/15283365/SQL_2019_Express_ARM64_20240510170810.log)

**Comment by jimm98y** [comment]
In your case some of the SQL server is already installed and the SQL Express setup has detected that part (most likely from the failed installation attempt you did before) and returned an error code. You have to remove the SQL Express before running the installers. Ideally, if you have a VM snapshot from before the installation, you should revert to it. If you don't have it and you cannot uninstall SQL Express from Add/Remove programs, then you'll have to clean up the files and registry manually before attempting to install again.

**Comment by rda874** [comment]
Gotcha! thanks for the detailed explanation (I am not a programmer, but I am learning!)

**Comment by rda874** [comment]
Victory!
<img width="606" alt="Screenshot 2024-05-11 at 11 12 29 AM" src="https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/assets/160538570/9917e33a-6980-4eee-98ec-07626a99f7e3">

Thanks again.
