### ISSUE TITLE
Looking for SQL Server 2019 Setup sequence

### ISSUE THREAD

**Issue by rda874** [jimm98y/MSSQLEXPRESS-M1-Install#34]
Hello, after successfully using your script to install SQL Server 2019 Express, I have been trying to get it to recognize a previously installed version of ACT!  It seems that I need the SQL setup sequence to do this. Is this part possible? I provided the link to the ACT! knowledge article for reference. thank you!

[How to manually create the Microsoft SQL Server 2019 ACT7 Instance](https://help.act.com/s/article/How-to-manually-create-the-Microsoft-SQL-Server-2019-ACT7-Instance-prem?language=en_US)

**Comment by jimm98y** [comment]
I have no idea what ACT is, but briefly looking at the steps it might be possible. You would have to modify the SQL instance name, change it to run as SYSTEM (can be done in Windows), enabling TCP/IP is not possible using GUI like they show, but it is possible using Windows Registry (see https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/issues/4). Setting the sa user is possible in SQL Management Studio. The rest looks like running some bat file that just executes SQL commands, so it might be doable...

**Comment by rda874** [comment]
Ok thanks for your help!
