### ISSUE TITLE
Surface pro 11 x

### ISSUE THREAD

**Issue by WW70ODY** [jimm98y/MSSQLEXPRESS-M1-Install#37]
Had problems with the initial installation on the new surface pro 11.  Would not install or work correctly with SSMS v20 installed.  Had to remove SSMS, install sqlserver dev 2022 using the bat file and then install SSMS v18 as v20 appears to prevent the SQL server service to start for some reason.
Not really an issue now but just a note for reference.

**Comment by maggimats** [comment]
@WW70ODY I'm trying to install SQL Server on my Surface Pro 11 (X Plus processor) but setup always fails. Can you help me by explaining a little bit more how you succeeded please ?

**Comment by jimm98y** [comment]
@maggimats Could you please share the log from the setup?

**Comment by maggimats** [comment]
I finally made it to work with 2019 version but then couldn't login. Thanks to [this comment](https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/issues/31#issuecomment-2108967268), the elevated rights made it work as it was using a managed service account.
