### ISSUE TITLE
the recent update is not work

### ISSUE THREAD

**Issue by yahiaalnaqeeb** [jimm98y/MSSQLEXPRESS-M1-Install#38]
i used it before 1 year , it was prefect, 

now i installed moved to new mac , when i try above  it is succecc instaltion , 
but when i try to connect or open sqlserver with windows authentaction does not work ever .

**Comment by jimm98y** [comment]
Please see https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/issues/36 if it helps. The old version had to fiddle with user accounts to make it work, while the new version completes the installation and configures the system on its own, I no longer interfere with the config.
