### ISSUE TITLE
How asign password to sa user?

### ISSUE THREAD

**Issue by msolorzano77** [jimm98y/MSSQLEXPRESS-M1-Install#39]
i try to assign password to 'sa' user, but i cant login
please help

**Comment by jimm98y** [comment]
When you install as Admin, you should be able to use SQL Server Management Studio running also as Admin. Windows Authentication should let you connect. If you are having issues with the standard approach, you can always use sqlcmd.exe running locally on the same machine as the SQL Server and you can enable the "sa" user as described here: https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/issues/36
