### ISSUE TITLE
[Windows 11 + M3] Issue starting SQL Server instance?

### ISSUE THREAD

**Issue by andyepifani** [jimm98y/MSSQLEXPRESS-M1-Install#40]
I am trying to install SQL Server Express 2019 on Windows 11 (VMWare, M3 but also Parallels, M3) using these scripts, but the database can't be started for unknown reasons... Any tips / anyone succeeded at getting this setup work? 

Thank you 🙌

**Comment by RuiPedroLeal** [comment]
Hello. I have the exact same problem. Running Windows 11 ARM on a M3 MacBook Air via UTM. Executed this script, managed to install the SQL Server, SSIS, SSAS, but the SQL Server instance never starts. Any suggestions?

**Comment by RuiPedroLeal** [comment]
Quick update. Managed to install it and run it by completely remove any installation of sqlserver I had. Then executed the .BAT file again x2 (don't know why, but I had to do it 2 times). After that the SQL Server Installation was ok and running. Managed also to open the installer/setup and configured the Integration Services and Analysis Services.

**Comment by sudoagile** [comment]
Logre instalar el sql 2019 dev en mi surface 11, llego hasta aqui, cual seria la contraseña del usuario sa

![Dos](https://github.com/user-attachments/assets/453f17b8-957f-4f95-8c8a-1065d060c8bd)
![Uno](https://github.com/user-attachments/assets/5d77c124-25c3-4991-880c-fe419d97576f)

**Comment by Akbb777** [comment]
@jimm98y  hi
Can you please check the screenshot? I’m running windows 11arm and can’t get tecne sql instance to start?

it gives up error 1067 all the time. 

I’m able to run the sql server as per your directions 

Please advise
![IMG_0447](https://github.com/user-attachments/assets/7091d2b6-8cc7-4e39-8583-60ca8113facb)

**Comment by Akbb777** [comment]
the issue is still same

can you please see the screenshot?
The instance TECNE fails to works and gives up error.

I am running windows 11 arm in parallels.

Please help- as I got SQL Service to run by guide given by jimmy98

**Comment by sudoagile** [comment]
El mensaje de error indica que hay un problema para conectarse al servidor SQL. Aquí algunos pasos para solucionar este problema:

  1.  Verificar el nombre del servidor:
     *   Asegúrate de que el nombre del servidor AKKY35AC\TECNE esté correctamente escrito.
     *   Verifica si la instancia TECNE está configurada correctamente en el servidor SQL.
  2.  Asegurar que el servidor SQL esté en ejecución:
     *   Abre el Administrador de configuración de SQL Server.
     *   Confirma que el servicio de SQL Server para la instancia mencionada está en ejecución.
  3.  Habilitar conexiones remotas:
     *   En el servidor SQL, habilita las conexiones remotas:
        *   Abre "SQL Server Management Studio" (SSMS).
        *   Haz clic derecho sobre el servidor y selecciona "Propiedades".
        *   En la pestaña "Conexiones", asegúrate de que la opción "Permitir conexiones remotas a este servidor" esté activada.
  4.  Configurar los protocolos de red:
     *   En el "Administrador de configuración de SQL Server":
        *   Habilita los protocolos TCP/IP y Named Pipes para la instancia TECNE.
     *   Asegúrate de que el puerto predeterminado (1433 para TCP/IP) esté abierto.
  5.  Configurar el Firewall:
     *   Si estás intentando conectarte desde otro equipo, asegúrate de que el Firewall permita conexiones en el puerto usado por SQL Server (normalmente 1433).
  6.  Probar conectividad:
     *   Intenta hacer un ping al nombre del servidor desde el cliente para verificar conectividad.
     *   Usa herramientas como telnet AKKY35AC 1433 para probar la conectividad del puerto.
  7.  Verificar las credenciales de acceso:
     *   Asegúrate de que estás utilizando las credenciales correctas (usuario y contraseña).

Esa es una repuesta de Chat GTP, yo con eso me ayude a solucionar mi probema
De: Akbb777 ***@***.***>
Enviado el: miércoles, 20 de noviembre de 2024 3:47
Para: jimm98y/MSSQLEXPRESS-M1-Install ***@***.***>
CC: EDUARDO RAMIREZ DE LAMA ***@***.***>; Comment ***@***.***>
Asunto: Re: [jimm98y/MSSQLEXPRESS-M1-Install] [Windows 11 + M3] Issue starting SQL Server instance? (Issue #40)


Screenshot.2024-11-19.172814.png (view on web)<https://github.com/user-attachments/assets/ae1be801-705f-49c7-9b6e-67f3d2b5098a>
Screenshot.2024-11-20.115752.png (view on web)<https://github.com/user-attachments/assets/a078cb50-7923-4390-ab55-6d45cd44e353>

the issue is still same

can you please see the screenshot?
The instance TECNE fails to works and gives up error.

I am running windows 11 arm in parallels.

Please help- as I got SQL Service to run by guide given by jimmy98

**Comment by Akbb777** [comment]
1.  Verify server name:

* Make sure that the server name AKKY35AC\TECNE is correctly written. Yes everything written correctly

* Verify that the TECNE instance is correctly configured on the SQL server- please can you confirm steps to do this?

2. Ensure that the SQL server is running:

* Opens the SQL Server Configuration Manager.

* Confirm that the SQL Server service for the mentioned instance is running- no it’s not running- it throws error 1067 on windows 11 arm

3. Enable remote connections:

* On the SQL server, enable remote connections: yes enable

* Opens "SQL Server Management Studio" (SSMS).

* Right-click on the server and select "Properties".

* In the "Connections" tab, make sure that the "Allow remote connections to this server" option is enabled.

4. Configure network protocols:

* In the "SQL Server Configuration Manager":

* Enables TCP/IP and Named Pipes protocols for the TECNE instance.- yes all enabled

* Make sure the default port (1433 for TCP/IP) is open- how to do this? Please help?

5. Configure the Firewall:

* If you are trying to connect from another computer, make sure that the Firewall allows connections on the port used by SQL Server (usually 1433)- using same computer and script from Lukas to emulate the sql service

6. Test connectivity:

* Try to ping the server name from the client to verify connectivity.

* Use tools such as telnet AKKY35AC 1433 to test port connectivity.

7. Verify access credentials:

* Make sure you are using the correct credentials (username and password)- yes under windows authentication- all credentials are correct
* 


Thanks till now. I think we are close to configuring this. 

I am now changing the bat file and putting in the instance tecne and trying 

please help and troubleshoot. I am really grateful

**Comment by sudoagile** [comment]
El error 1067 en SQL Server generalmente indica que el servicio no pudo iniciarse debido a problemas con la configuración, permisos o compatibilidad. Aquí tienes una guía para solucionarlo paso a paso:
________________________________
1. Verificar los registros de errores

  *   Revisa los registros de errores de SQL Server para entender por qué no puede iniciarse:
     *   Ve al directorio de instalación de SQL Server, usualmente:
C:\Program Files\Microsoft SQL Server\MSSQL{VERSION}.\MSSQL\Log
     *   Abre el archivo más reciente (ERRORLOG) con un editor de texto.
     *   Busca mensajes que indiquen el problema exacto.

________________________________
2. Verificar la configuración de la instancia
Asegúrate de que la configuración básica de la instancia es correcta:

  *   Abre el Administrador de Configuración de SQL Server.
  *   Busca el servicio SQL Server (TECNE) y haz clic derecho → Propiedades:
     *   En la pestaña Log On, asegúrate de que el servicio está configurado para ejecutarse con la cuenta de servicio adecuada (por defecto, NT Service\MSSQL$<NOMBRE_INSTANCIA>).
     *   Si hay problemas con la cuenta de servicio:
        *   Cambia la cuenta a Local System y prueba si el servicio se inicia.

________________________________
3. Revisar la configuración del archivo sqlservr.exe
En algunos casos, el archivo ejecutable (sqlservr.exe) puede estar mal configurado:

  *   Ve al directorio donde se encuentra la instancia TECNE:
     *   Ejemplo: C:\Program Files\Microsoft SQL Server\MSSQL{VERSION}.TECNE\MSSQL\Binn\
  *   Asegúrate de que el archivo sqlservr.exe está presente.
  *   Intenta iniciarlo manualmente ejecutándolo desde la línea de comandos.

________________________________
4. Configurar la compatibilidad para Windows 11 ARM
Dado que estás en Windows 11 ARM, puede haber problemas de compatibilidad. Realiza lo siguiente:

  *   Forzar compatibilidad x64 (emulación):
     *   Asegúrate de que el instalador de SQL Server es compatible con ARM (algunos no lo son).
     *   Si usas un script para emular, revisa que esté configurado para ARM64.
  *   Si el script es de "Lukas" como mencionaste, verifica las configuraciones personalizadas o consulta documentación específica.

________________________________
5. Restablecer la base de datos master
Si la base de datos master (crucial para que arranque SQL Server) está dañada:

  1.  Inicia SQL Server en modo mínimo:
     *   Entra al directorio de la instancia desde la terminal y ejecuta:
Copiar código
sqlservr.exe -s TECNE -f

     *   Esto inicia SQL Server en un modo mínimo, permitiéndote corregir problemas.
  1.  Si funciona, revisa y corrige errores en la configuración o bases de datos.

________________________________
6. Verificar permisos de carpetas
SQL Server necesita permisos específicos en sus carpetas:

  *   Ve al directorio de datos de tu instancia (normalmente en C:\Program Files\Microsoft SQL Server\MSSQL{VERSION}.TECNE\MSSQL\DATA).
  *   Asegúrate de que la cuenta de servicio tiene permisos lectura/escritura en estas carpetas:
     *   Haz clic derecho en la carpeta → Propiedades → Seguridad.

________________________________
7. Probar reinstalación de la instancia
Si todo falla, puedes intentar reinstalar la instancia:

  1.  Desinstala solo la instancia TECNE desde el panel de control.
  2.  Instálala de nuevo asegurándote de seleccionar configuraciones predeterminadas.
  3.  Prueba iniciar el servicio.

________________________________
8. Verificar puertos y protocolos
Si los pasos anteriores funcionan pero no puedes conectarte:

  *   Confirma que el puerto 1433 está configurado para la instancia TECNE:
     *   En el Administrador de configuración de SQL Server, selecciona Protocolo TCP/IP.
     *   Abre las propiedades y verifica que el puerto TCP predeterminado es 1433.
     *   Habilita todas las direcciones IP necesarias (en especial 127.0.0.1 para localhost).


De: Akbb777 ***@***.***>
Enviado el: miércoles, 20 de noviembre de 2024 11:51
Para: jimm98y/MSSQLEXPRESS-M1-Install ***@***.***>
CC: EDUARDO RAMIREZ DE LAMA ***@***.***>; Comment ***@***.***>
Asunto: Re: [jimm98y/MSSQLEXPRESS-M1-Install] [Windows 11 + M3] Issue starting SQL Server instance? (Issue #40)


  1.  Verify server name:

  *   Make sure that the server name AKKY35AC\TECNE is correctly written. Yes everything written correctly
  *   Verify that the TECNE instance is correctly configured on the SQL server- please can you confirm steps to do this?

  1.  Ensure that the SQL server is running:

  *   Opens the SQL Server Configuration Manager.
  *   Confirm that the SQL Server service for the mentioned instance is running- no it’s not running- it throws error 1067 on windows 11 arm

  1.  Enable remote connections:

  *   On the SQL server, enable remote connections: yes enable
  *   Opens "SQL Server Management Studio" (SSMS).
  *   Right-click on the server and select "Properties".
  *   In the "Connections" tab, make sure that the "Allow remote connections to this server" option is enabled.

  1.  Configure network protocols:

  *   In the "SQL Server Configuration Manager":
  *   Enables TCP/IP and Named Pipes protocols for the TECNE instance.- yes all enabled
  *   Make sure the default port (1433 for TCP/IP) is open- how to do this? Please help?

  1.  Configure the Firewall:

  *   If you are trying to connect from another computer, make sure that the Firewall allows connections on the port used by SQL Server (usually 1433)- using same computer and script from Lukas to emulate the sql service

  1.  Test connectivity:

  *   Try to ping the server name from the client to verify connectivity.
  *   Use tools such as telnet AKKY35AC 1433 to test port connectivity.

  1.  Verify access credentials:

  *   Make sure you are using the correct credentials (username and password)- yes under windows authentication- all credentials are correct
  *

Thanks till now. I think we are close to configuring this.

I am now changing the bat file and putting in the instance tecne and trying

please help and troubleshoot. I am really grateful

**Comment by Akbb777** [comment]
Please help
