### ISSUE TITLE
Unable to login to sql with windows authentication? How can I login ?

### ISSUE THREAD

**Issue by taddeozanga** [jimm98y/MSSQLEXPRESS-M1-Install#42]
I installed sql management studio and I'm trying to login but it doesn't work with windows authentication? is there an SA account I can use? please help

**Comment by taddeozanga** [comment]
Ok I resolved it myself, although my user is an administrator it wasn't added to SQL. So I enabled the standard Administrator account and I was able to login to SQL that way and then I successfully added my user...

I would suggest adding the parameter "/ADDCURRENTUSERASSQLADMIN" to the installation script I think this would solve the issue.

**Comment by andrewgabler** [comment]
How exactly did you manage to do that? I cannot get the admin account to switch in the login screen even after changing it in the configuration manager to be the login user.

**Comment by justinhca** [comment]
I was able to resolve this by running SSMS in Admin mode.

**Comment by danieljin** [comment]
Instead of just running in admin mode, you can add your current user as a new login.

![image](https://github.com/user-attachments/assets/b2220db4-42a9-436a-8950-a25f890ebd3d)

I followed instructions from here: https://superuser.com/a/1386437
