### ISSUE TITLE
[Question] Install SQL Express and SQL Deveopler side by side

### ISSUE THREAD

**Issue by cigoic** [jimm98y/MSSQLEXPRESS-M1-Install#43]
hi,

When I use the released exe files to install both SQL Server versions, one will be removed by the other. Is there any way to install both versions on the same machine with the same account?

For example, I installed SQL Express first and successfully executed it without problem. A Developer version will fit to my on going project. Therefore, I tried to install it. The installation progress fail at first time, but success at second attempt. However, it won't connect to the sever with my windows account which works on Express version (via Windows authorization). The error shows that it cannot recognize the user account.

Would you please release another version support both installations at the same time? Thanks a lot!

**Comment by jimm98y** [comment]
You can use the scripts to install the second SQL server: https://github.com/jimm98y/MSSQLEXPRESS-M1-Install/tree/main/src/Scripts 

As for the connectivity issues, you can always use the standard SQL way of recovering SQL access by using sqlcmd.exe: https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out?view=sql-server-ver16

**Comment by cigoic** [comment]
Thanks. I will give it a try.
