### ISSUE TITLE
It does nothing

### ISSUE THREAD

**Issue by Gn0m4** [jimm98y/MSSQLEXPRESS-M1-Install#8]
Mac Mini M1 on Ventura 13.1
Parallels Desktop 18.1.1
Windows11_InsiderPreview_Client_ARM64_en-us_25267
Updated

Double click on any .bat file of the src, CMD is opened and closed in half second.

**Comment by azinsharaf** [comment]
Edit the batch file by adding a "pause" word (without double quotes) to the second line, save and run it again.

**Comment by jimm98y** [comment]
The bat file is just a convenient shortcut for running the PowerShell script. Clicking it should open PowerShell in a new window. If it does not, you can also run the PowerShell script directly.

Open PowerShell (or Windows Terminal) as Administrator and navigate to the folder with the scripts. Run:
Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
./install2019Express.ps1

If it fails for some reason, please send me the output of the PowerShell script.

**Comment by Gn0m4** [comment]
> 

![Screenshot 2023-02-08 092038](https://user-images.githubusercontent.com/115212070/217473768-90b4e5b5-51d0-4dc3-a700-64d9980b5c4c.jpg)

Then push any key and close again.

**Comment by Gn0m4** [comment]
> The bat file is just a convenient shortcut for running the PowerShell script. Clicking it should open PowerShell in a new window. If it does not, you can also run the PowerShell script directly.
> 
> Open PowerShell (or Windows Terminal) as Administrator and navigate to the folder with the scripts. Run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process ./install2019Express.ps1
> 
> If it fails for some reason, please send me the output of the PowerShell script.

![Screenshot 2023-02-08 091727](https://user-images.githubusercontent.com/115212070/217474028-12a24749-25fb-447e-9510-805fabc82641.jpg)

**Comment by jimm98y** [comment]
Well, it's 2 commands:

Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process

[Enter]

./install2019Express.ps1

[Enter]

**Comment by Gn0m4** [comment]
> 

<img width="484" alt="Captura de pantalla 2023-02-08 a las 8 49 25" src="https://user-images.githubusercontent.com/115212070/217773525-2d8b8402-1a63-4a7b-9173-abbe6ac4100a.png">

**Comment by Gn0m4** [comment]
> Well, it's 2 commands:
> 
> Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
> 
> [Enter]
> 
> ./install2019Express.ps1
> 
> [Enter]

![Captura de pantalla 2023-02-09 103418](https://user-images.githubusercontent.com/115212070/217773881-dc90e072-cfe8-491d-b541-bb0e3e3170e4.jpg)

**Comment by briannicholas** [comment]
You've downloaded the HTML pages not the scripts. I'd guess you right clicked save as on the links

If you want to do that you need to save as on the "Raw" links or grab them from here

https://raw.githubusercontent.com/jimm98y/MSSQLEXPRESS-M1-Install/main/src/install2022Express.ps1

https://raw.githubusercontent.com/jimm98y/MSSQLEXPRESS-M1-Install/main/src/install2022Express.bat

**Comment by Gn0m4** [comment]
> You've downloaded the HTML pages not the scripts. I'd guess you right clicked save as on the links
> 
> If you want to do that you need to save as on the "Raw" links or grab them from here
> 
> https://raw.githubusercontent.com/jimm98y/MSSQLEXPRESS-M1-Install/main/src/install2022Express.ps1
> 
> https://raw.githubusercontent.com/jimm98y/MSSQLEXPRESS-M1-Install/main/src/install2022Express.bat

Thanks for your answer.
After download files from your links it works !!!
I don´t know the reason cause the other files i downloaded aren´t html pages... even Edge ask me to be caution because the bat file so... anyway there are lot of errors.
Yesterday I left the installation and today no changes at all...


![Captura de pantalla 2023-02-09 173934](https://user-images.githubusercontent.com/115212070/218035633-b926e32b-3305-47fa-8008-f20b4c8fbd17.jpg)
![Captura de pantalla 2023-02-09 173947](https://user-images.githubusercontent.com/115212070/218035667-f0c7d5b1-7b52-45f2-a772-af0756cfd7ea.jpg)

**Comment by jimm98y** [comment]
Copy the script to a local folder (C:\Temp) and run it from there. It looks like you are trying to run it from a network file path which won't work as the PowerShell cannot access it.

**Comment by Gn0m4** [comment]
Perfect. Thanks to all for the support!
