### ISSUE TITLE
File Path

### ISSUE THREAD

**Issue by Tjiffels** [jimm98y/MSSQLEXPRESS-M1-Install#9]
Hi Jimmy,

Thanks for the excellent work, it is much appreciated! I just want to mention that I encountered errors when trying to install any of the developer versions. I figured out what the problem was and I think you must just mention it on your guide. It seems like if the file path to  the scripts location is too long, the setup fails. So what I did was 'n created a folder on the C drive, and put the scripts in there. After that the install worked like a charm!

I just thought I should mention!

Have a nice day further!

**Comment by jimm98y** [comment]
Yes, that's an OS limitation. Thank you for mentioning it along with the solution, it might help somebody.
